### ISSUE TITLE
Possible memory corruption due to malloc

### ISSUE THREAD

**Issue by ando23** [Absurdponcho/YoutubeOS#3]
Currently, malloc tries to split every free segment. This fails when the current free segment does not have enough space for another  MemorySegmentHeader by (partially) overwriting the next segment.

Example:
```
auto p1 = malloc(0x10);
auto p2 = malloc(0x10);
auto p3 = malloc(0x100);
free(p1);
free(p2);
```
This yields a gap of 0x50 (0x10 + 0x10 + sizeof(MemorySegmentHeader)) at the start of the heap.

Now, if we do
`auto p4 = malloc(0x40);`
This will return the same address as p1, but the segment header for p3 is damaged.

After that, further malloc and free operation can crash the OS since the pointers may be invalid.

Possible fixes:
* select free segments only if there is space for another MemorySegmentHeader
* don't split if the remaining space is not enough. In that case return the whole segment.

**Comment by Absurdponcho** [comment]
p1 and p2 take up 0x80 bytes because there is 2 allocated blocks and 2 memorysegmentheaders. 
therefore allocating 0x40 is valid because there is 0x80, required 0x70

However I can see there is an issue here, I'll see what I can do

**Comment by Absurdponcho** [comment]
I've updated the branches with the new fixed malloc function, and am reuploading the malloc video (again lol). Let me know if there are any more issues. thank you
